---
creation_rules:
  - # IMPORTANT: This rule MUST be above the others
    path_regex: talos/.*\.sops\.ya?ml
    key_groups:
      - age:
          - "age1w3dy7lwml0m54a8wg6lzt05jlxa09tlxjtxl5q98sexdnwry7exqem30lk"
  - path_regex: kubernetes/.*\.sops\.ya?ml
    encrypted_regex: "^(data|stringData)$"
    key_groups:
      - age:
          - "age1w3dy7lwml0m54a8wg6lzt05jlxa09tlxjtxl5q98sexdnwry7exqem30lk"
