apiVersion: v1
kind: Secret
metadata:
    name: cluster-secrets
    namespace: flux-system
stringData:
    SECRET_DOMAIN: ENC[AES256_GCM,data:bxza3TF3nCi1MaxPvRI=,iv:RJ9fHqSic5chULplCx4M8GZTBCKorTbh+zsBQnG947k=,tag:DMlLvUWHwYTL275SbFKTNg==,type:str]
    SECRET_ACME_EMAIL: ENC[AES256_GCM,data:M+NE8JplMeYlGRsw0anlmrbmag4=,iv:r75RNccB4IHIDAMw7V1Yp0RJTT4VRmN8wGDLUtVBzdo=,tag:7oddOGtOb1B30bWw8HNGtQ==,type:str]
    SECRET_CLOUDFLARE_TUNNEL_ID: ENC[AES256_GCM,data:gYt9d0VaRXLcOGeeR45DX6OURPE9fCIgMOwg1Rb/KC4zOUgZ,iv:dF6o52RuK2g9fXycvTO2OSqqSTBnRE4CbYEEpBHwC3c=,tag:ToIB8OB/j7TpRFLdTU/T1A==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1w3dy7lwml0m54a8wg6lzt05jlxa09tlxjtxl5q98sexdnwry7exqem30lk
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAzbHlsOFhoSFlLM2xVTGNM
            VU1NUW5raGNCeUJYU0haM1g1OE9uZnNnZ0g0CjlsUkNCRHoxaGtXTUVQZi9uN2VX
            aThhKzJKcWt4SFJVQXI5OGsrME91a1UKLS0tIFluZlJGcEN2K09NQVc3TDUzQndk
            TkM3TmZNeW9VQU5HUitzVFJFWnlKUVkKzJu1WO5d7GNsK6zyY1b028Ovn6fwlNYS
            R7UoHSVCvSLjVKJlEwcAqhqtXRhPcfXeSCRCgwnBHU6+Z/Omp5bJDw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-08-30T04:28:04Z"
    mac: ENC[AES256_GCM,data:MJ8Io6fvuify9z0yG2rFjEx2Phk3yFGxE7KWoMePzL7W+mEI8rcuZRa1kOv18HPsehq5uxaBz6UrhMZ0h3hIAcwvo+wKFYRPSnC9CLiU7lOdG+pTTg6zO/W5LRnBcdWyHpSIOUkrZ+7fxPc+DwRlNiOhFTcPQE7b3kMGazy16So=,iv:L7nEFPSbGA9cVOwkG9U8Ml2vpWmNby4KyIJLudo5EV4=,tag:eH4MSM6t+8loW/okWOTHnQ==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.0
