apiVersion: v1
kind: Secret
metadata:
    name: github-webhook-token-secret
stringData:
    token: ENC[AES256_GCM,data:sA8FtlE5xX9bTxvGzROWkpqSwICuhS26ipIfeOBNBkI=,iv:Fjos9JbRn5bm5QUNY6XggIs7lGOrDGJwCAsHiIMNYMM=,tag:+XAWOmoOxdUWnvs9pj2vaw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1w3dy7lwml0m54a8wg6lzt05jlxa09tlxjtxl5q98sexdnwry7exqem30lk
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBIVDBYYnpFR25GOVNDaVhI
            OE5ablVKRmR4cGlqRWhLemRHRlZWaytRMUFFCmwyN1RaMVR0ck9IckNRcVB5TjdJ
            VWtsRnROUEpVa0JkV3FKR01FSHBkWjAKLS0tIHE2b0YrVGJVR2RiK29NSllrTC9v
            NWhOYWJDTkhlTmwrcVdmbFdLU053c1EKsbSu+kC7rc0+AnncJWaN/Z6oNj5OCN3a
            cTaPON7W4PMqnehsnK3pIAuHB7S0k9UBa+Dpj4eB4q20t2vY4oH9sA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-08-30T12:39:54Z"
    mac: ENC[AES256_GCM,data:plp9MCPw38thZDaoS7h67jswuRm8Gtfg/MdW/HhO1+nHHA2CcqHFpXN7t/FGkb5orDOnFmhOZucgm44/xmefFwZSLtdsksuyjMyciJsWIZQpH7YtpjfaxEIASOmds8ZABQ+hiYCdtKMxx9q3UVRCl852N8KnGh+XMsedWIMSR3Y=,iv:V/r1STl7tEKOhoP+pXmwbkuVXxGAUzLN7PMgVNqE9Ws=,tag:jirHZeSm7OTTo5YtAUB93w==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.0
