apiVersion: v1
kind: Secret
metadata:
    name: external-dns-secret
stringData:
    api-token: ENC[AES256_GCM,data:aGlDZ/XgKWoUD7iVqHUcl6zlCj4VK/M5r1i9kY9aB5fakSsYf+3Mjw==,iv:oD6nMF8fNl5HSs1j4AKyAFqJtg345sjl6Nok+AdeGGE=,tag:P5Pp5MbBpKmX3pGabljacw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1w3dy7lwml0m54a8wg6lzt05jlxa09tlxjtxl5q98sexdnwry7exqem30lk
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBaaGEzVWsyNTh0V2x2MlA0
            dGpoTGlEbjFRYVVnOFZ6eFl5bXFoUzJDaW1JCkRZT0I3ek1TYjZvUklaRGw2RXpr
            MC82QVArcWUrK0RFUUNlS09CeFNrb2sKLS0tIHNBQ2tZMXR0aFNzdkN5d3pZcFAw
            MHZNcGYxTUd4RGNxMmJZRDVyS2tUYTAK4V39ib9AnWh0TXkELF9SeuUNiAlgBX6x
            hFysZP18PYwUHYucXWh4AYWXHFOD0JL/Y71tbyj+ieU0hlf1dyhU6g==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-08-30T12:39:54Z"
    mac: ENC[AES256_GCM,data:r6bUNp8bSHTS1b7jJgbs8KM5cXD/BHn6p757uSkszQvOoDEEB2WOTKU/p4qtOH2TPoiB9/wbHM0VyZG/X2wGXLnd3D1b+bna+X2pO2y+9onSz55n+ZP2uEDWVCad2xub714hOQ0VjpeuPBpxlmNI+2x3VXFi9NCSZF/xo0CtQhs=,iv:9Bf9S5ka9JkNnHPwmQsuRX3T3KseXjJMC7AT8jzHJWk=,tag:PHrBu94p/pErUPgaqUmBFw==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.0
