apiVersion: v1
kind: Secret
metadata:
    name: external-dns-secret
stringData:
    api-token: ENC[AES256_GCM,data:HJlRiaEZZpfEWYkR7fQ14DFpbfcGYOlE2ItLPpAvUNjIK+HApdr2Fw==,iv:7fWHbsGCs8hBp0/prSQhgz3JNZ9IhBayJbnpKDSimVE=,tag:X+80rUU2iXeWwJx2oPi08A==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1w3dy7lwml0m54a8wg6lzt05jlxa09tlxjtxl5q98sexdnwry7exqem30lk
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAwclFXOUxSV1g3M3BnRjB0
            OWZpTGtram5hcGVsNms2UThOeE05cXBCTTBBClZlM25Ec2tHL2RLV0JxT0VES0lp
            bzJqODFtbjE0SUppQ1lVQ084TVJUR0UKLS0tIEJ5OW45clowOGRCZEs4Vy96Qk9W
            QWhMdDR6M2ZXZ25YL1Z1NGdUbHJEb0UK1zbwS0nJqUxAwHNJiyzxnZKGBY5g1W1s
            szpSbvOrwDm/j1ZR79BY2kOr3BWoB61Ua+OjKmbnbleiceTxhrPM1g==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-08-30T04:28:04Z"
    mac: ENC[AES256_GCM,data:4aDslaX7Ulqwi3oLhvA7+PTMcQW/oVUgW4ljqvT67Bljwh+pmzqBJFFhAEPFc7DFBl6dt73MhyYpeYyTCtnVQ2Xq0cz1/tvxF4MOJ2AlNwW8/1FXa+Qm4yzpJogbuDDQ8D+SWDkvaYt3/14kKQeDMwhQWnCoRczl16md/h9PemI=,iv:PjWrRfZmkk5DBSWVFcyUBCqd0ySrPmAXZUmQWmcihuE=,tag:EfCtSGqhmzm9tf0KOkk3tg==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.0
